### ISSUE TITLE
Meta Data Language

### ISSUE THREAD

**Issue by fisherstevenk** [swiftcryptollc/swiftcryptollc.github.io#41]
Meta Language tag missing
- 1 instance found
How to fix?
What is the issue about?
The Meta Language information is used as a hint to help us understand the intended language and country/region the page content applies to. This can help if your site is not hosted in the country/region. Use the “content-language” meta tag to embed the culture code in the <head> section of your page. For example, <meta http-equiv='content-language' content='en-gb'> indicates that the page is in English and intended for the the United Kingdom. Alternatively, you can use <html lang='en-gb'> or <title lang='en-gb' />.
How to fix?
Use <meta http-equiv='content-language' content='en-gb'> tag in the <head> section of your page, where 'en-gb' stands for the culture code of the language and country/region the content applies to. Alternatively use the lang='en-gb' attribute on either the <html> or the <title> tag .

**Comment by swiftcryptollc** [comment]
Added into #46
